version: '3.3'
services:
  ppp_viviendas-server:
    container_name: ppp_viviendas-server
#    build: .
    image: geo_viviendas_ppp:latest
    environment:
    - DB_USER=root
    - DB_PASSWORD=12345678
    - DB_URL=jdbc:mysql://db-viv:3307/ppp_viviendas?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    - SECRET_KEY=secreto
    ports:
    - 8081:8080
    volumes:
    - visitasPdf:/archivos

  db-viv:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ppp_viviendas
      MYSQL_TCP_PORT: 3307
    ports:
    - 3307:3307
    expose:
      - 3307
    volumes:
      - ./mysqlDB-viviendas:/var/lib/mysql

  adminer-viv:
    image: adminer
    restart: always
    ports:
      - 8091:8080

volumes:
  visitasPdf:
